// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqwdosktzpdcyjvykprs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxd2Rvc2t0enBkY3lqdnlrcHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDM2MDcsImV4cCI6MjA3MjYxOTYwN30.NAoF3LDgcEoWTA50n3I38fIKh8a1Zp6REj5O4r1zYVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});